<?php

use \Drupal\node\Entity\Node;
use \Drupal\user\Entity\User;
use \Drupal\taxonomy\Entity\Term;
use \Drupal\file\Entity\File;
use \Drupal\Core\Form;
use \Drupal\Core\Form\FormStateInterface;
use \Drupal\user\Entity\Role;
use \Symfony\Component\HttpFoundation\RedirectResponse;

function aeiraresources_preprocess_page(&$variables) {
  // get a hold of the node object
  /*$node = \Drupal::routeMatch()->getParameter('node');
  if ($node) { // check we have a node object.
    if ($node->id() == 2) { // look for a specific node id.
      //attach the library.
      $variables['#attached']['library'][] = 'aeiraresources/frontpagemap';
    }
  }
  */
  // Attach library
  $variables['#attached']['library'][] = 'aeiraresources/frontpagemap';
  
  // Make aeira settings available from JS
  $config = \Drupal::config('aeiraresources.settings');
  $variables['#attached']['drupalSettings']['lat'] = $config->get('aeira_lat');
  $variables['#attached']['drupalSettings']['lon'] = $config->get('aeira_lon');
  $variables['#attached']['drupalSettings']['zoom'] = $config->get('aeira_zoom');
}

  /**
   * Implements hook_menu().
   */
  function aeiraresources_menu() {
    $items['admin/config/aeiraresources/settings'] = array(
      'title' => 'Aeira configuracións',
      'description' => 'Permite personalizar as opcións xerais do sitio.',
      'route_name' => 'aeiraresources.settings',
    );

    return $items;
  }