<?php

use \Drupal\node\Entity\Node;
use \Drupal\user\Entity\User;
use \Drupal\taxonomy\Entity\Term;
use \Drupal\file\Entity\File;
use \Drupal\Core\Form;
use \Drupal\Core\Form\FormStateInterface;
use \Drupal\user\Entity\Role;
use \Drupal\Core\Url;
use \Symfony\Component\HttpFoundation\RedirectResponse;


/** 
 * Implements hook_preprocess_page(). 
 */ 
function aeiraresources_preprocess_page(&$variables) {
  $current_url = Url::fromRoute('<current>');
  $path = $current_url->toString();

    if ($path == '/mapa') {
        // Attach library
        $variables['#attached']['library'][] = 'aeiraresources/frontpagemap';
    }
  // Make aeira settings available from JS
  $config = \Drupal::config('aeiraresources.settings');
  $variables['#attached']['drupalSettings']['lat'] = $config->get('aeira_lat');
  $variables['#attached']['drupalSettings']['lon'] = $config->get('aeira_lon');
  $variables['#attached']['drupalSettings']['zoom'] = $config->get('aeira_zoom');
  $variables['#attached']['drupalSettings']['map_uri'] = $config->get('aeira_base_map_uri');
  $variables['#attached']['drupalSettings']['map_attribution'] = $config->get('aeira_base_map_attribution');
}

/**
 * Implements hook_menu().
 */
function aeiraresources_menu() {
  $items['admin/config/aeiraresources/settings'] = array(
    
    'title' => 'Aeira configuracións',
    'description' => 'Permite personalizar as opcións xerais do sitio.',
    'route_name' => 'aeiraresources.settings',
  );

  return $items;
}